Grails 7
grails-plugins/grails-spring-security-cas pull request #107
Opened 2024-09-23 23:58 UTC by bkoehm

2024-09-30 12:59 UTC, jdaugherty approved these changes

2024-09-30 12:59 UTC, jdaugherty commented on .github/workflows/gradle.yml
>            distribution: 'adopt'
I believe we've been switching most projects away from adopt and to temurin. I'd suggest for this code review we update to match grails-core.

2024-10-01 14:48 UTC, jdaugherty commented on .github/workflows/release.yml
>            distribution: 'adopt'
We probably should update the release action to use temurin too.

2024-10-01 20:52 UTC, codeconsole requested changes

2024-10-01 20:52 UTC, codeconsole commented on testapps/spring-security-cas-test1/build.gradle
> +    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
This shouldn't be necessary when groovyVersion is set and grails-gradle-plugin is in the buildscript. 
Does it not work without it?

2024-10-01 20:52 UTC, codeconsole commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.1-bin.zip
Any chance you can update the wrapper to 8.10.2?

2024-10-01 20:52 UTC, codeconsole commented on testapps/spring-security-cas-test2/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.1-bin.zip
not sure why the extra wrappers are needed, but if you can update them as well to 8.10.2

Since they are subprojects, you should be able to run them from the root folder via `:testapp-spring-security-cas-test2'`

2024-10-01 20:52 UTC, codeconsole commented on testapps/spring-security-cas-test2/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.1-bin.zip
or just delete the wrappers from the subprojects if they aren't needed

2024-10-03 20:45 UTC, codeconsole commented
@bkoehm please seem my question regarding the `configurations {}` block

2024-10-07 19:26 UTC, codeconsole commented
@bkoehm I was referring to the `configurations.configureEach {}` block where you are forcing the version of gradle.   That should not be needed if you have `groovyVersion` set in `gradle.properties`

2024-10-08 21:40 UTC, codeconsole requested changes
@bkoehm 
 
```gradle
onfigurations {
    all {
        exclude group: 'javax.servlet'
        exclude group: 'javax.xml.bind'
    }
}
```

why is that needed in `plugin/build.gradle`?

2024-10-08 21:50 UTC, bkoehm commented
> @bkoehm
> 
> ```groovy-gradle
> onfigurations {
>     all {
>         exclude group: 'javax.servlet'
>         exclude group: 'javax.xml.bind'
>     }
> }
> ```
> 
> why is that needed in `plugin/build.gradle`?

Because there are dependencies that leak `javax.servlet` and `javax.xml.bind` (at least, there were a few days ago).

2024-10-09 03:44 UTC, codeconsole commented
> > why is that needed in `plugin/build.gradle`?
> 
> Because there are dependencies that leak `javax.servlet` and `javax.xml.bind` (at least, there were as of a few days ago).

I don't see anywhere where that should be the case.  If so, they should be updated to the latest version.

https://github.com/grails/grails-spring-security-cas/blob/545d30b342ea6b959d90a987d377458592c430c4/plugin/build.gradle#L65-L82

2024-10-10 14:48 UTC, bkoehm commented
> > > why is that needed in `plugin/build.gradle`?
> > 
> > 
> > Because there are dependencies that leak `javax.servlet` and `javax.xml.bind` (at least, there were as of a few days ago).
> 
> I don't see anywhere where that should be the case. If so, they should be updated to the latest version.
> 
> https://github.com/grails/grails-spring-security-cas/blob/545d30b342ea6b959d90a987d377458592c430c4/plugin/build.gradle#L65-L82
> 
> If it is ever the case, the preference is the exclusion on the dependency that has the older dependency.

Ok, removed.

2024-10-14 19:45 UTC, codeconsole commented
@bkoehm thanks, quick question, you deleted the second server. How is it tested now?  Do you just start the first server on a different port?

2024-10-14 19:49 UTC, bkoehm commented
> @bkoehm thanks, quick question, you deleted the second server. How is it tested now? Do you just start the first server on a different port?

Yes, the second test app was a dupe of the first one.  And it requires a working CAS server to test with.  It's not an automated test.

2024-10-14 20:05 UTC, codeconsole commented
> > @bkoehm thanks, quick question, you deleted the second server. How is it tested now? Do you just start the first server on a different port?
> 
> Yes, the second test app was a dupe of the first one. And it requires a working CAS server to test with. It's not an automated test.

Was there an automated test previously?

2024-10-14 21:49 UTC, bkoehm commented
> > > @bkoehm thanks, quick question, you deleted the second server. How is it tested now? Do you just start the first server on a different port?
> > 
> > 
> > Yes, the second test app was a dupe of the first one. And it requires a working CAS server to test with. It's not an automated test.
> 
> @bkoehm Was there an automated test previously? I am sure it would be easy enough to just pass the `port` at startup so removing it was the right call.

No, there wasn't.

2024-10-15 04:54 UTC, merged